### ISSUE TITLE
Information about Splunk detection

### ISSUE THREAD

**Issue by syrius01** [f8al/TA-Shell#1]
Hi,

Not sure if you could help me on this situation; I am trying to make a script that detects if Apache Splunk requires auth or not but I'm having a hard time since every time I get HTTP code 303, here's the PHP script so far;

https://pastebin.com/1JmH6rTU

Any help/suggestions would be very appreciated,

Thanks

**Comment by f8al** [comment]
so splunk doesnt run apache, it uses cherrypy for the webserver portion.  Its always going to require auth, especially if youre trying to get to 8089, or 8000, the difference is that pre splunk 4.1 admin:changeme worked remotely, after 4.1 if its still admin:changeme, you'll need to imitate that your request is coming from localhost, and after 7.x it no longer uses admin:changeme by default.  the auth methodology the rest api for splunk uses is just basic. Ive had great success crawling splunk installs with python and requests, so perhaps try that?
